Update AblyDeltaCodec dependency to 1.3.1
ably/ably-cocoa pull request #1165
Opened 2021-08-10 19:57 UTC by ben-xD

2021-08-10 20:21 UTC, maratal requested changes
Also Cartfile needs to be updated

2021-08-11 07:07 UTC, ben-xD commented
> Also Cartfile needs to be updated

I've also updated the Podspec. I also made the msgpack-objective-C version consistent between SPM, Carthage and Cocoapods. Previously Swift Package was using the latest version, by Cocoapods/ carthage was one version behind.

2021-08-11 07:09 UTC, lukasz-szyszkowski approved these changes

2021-08-12 11:13 UTC, maratal approved these changes

2021-08-12 13:59 UTC, merged