`transition:` method refactoring
ably/ably-cocoa pull request #1863
Opened 2024-01-28 22:38 UTC by maratal

Partially solves https://github.com/ably/ably-cocoa/issues/1858
This should be merged after https://github.com/ably/ably-cocoa/pull/1714

2024-01-30 18:29 UTC, sacOO7 requested changes

2024-01-30 22:08 UTC, maratal commented on Source/ARTRealtime.m
>              metadata.resumed = resumed;  // RTN19a
I got your point, I can just add one more parameter alongside metadata. But metadata is just a set of parameters. In this regard I would just rename it to `ARTConnectionStateChangeParams` or `ARTConnectionStateChangeArgs` as methods with a lot of parameters sometimes do, it's a common pattern. WDYT? @sacOO7 @lawrence-forooghian

2024-02-01 08:19 UTC, sacOO7 commented on Source/ARTRealtime.m
>              metadata.resumed = resumed;  // RTN19a
Yeah, I feel renaming is a good idea 👍

2024-02-02 14:33 UTC, maratal commented on Source/ARTRealtime.m
>              metadata.resumed = resumed;  // RTN19a
https://github.com/ably/ably-cocoa/pull/1863/commits/d75c5c1f0de9ef6f332a1d8a6c69484b02fa69ac

2024-02-05 15:00 UTC, sacOO7 approved these changes
LGTM

2024-02-12 18:43 UTC, lawrence-forooghian approved these changes

2024-02-23 02:02 UTC, merged